### ISSUE TITLE
Listing installed node versions

### ISSUE THREAD

**Issue by RobbieTheWagner** [jorgebucaran/nvm.fish#103]
Is there a way to list node versions? In normal nvm `nvm ls` typically lists the installed node versions and you are able to find and delete ones you no longer want. Is there an equivalent here?

**Comment by JGJP** [comment]
I too would like to have the ability to just see installed versions when using nvm ls. I don't need to see every single version of node that's available.

**Comment by jorgebucaran** [comment]
This works:
```console
ls ~/.config/nvm| awk /[0-9]/
```

We could also define `$nvm_config` in advance inside our configuration snippet (that runs when your shell starts) allowing:

```console
ls $config_nvm | awk /[0-9]/
```
...which you may consider a slight improvement.

---

Why isn't there a formal way to do this with fish-nvm out of the box? 

Because fish-nvm doesn't have this notion of "installed" & "installable" versions. I just don't care what versions I've already downloaded. And that's why there's no `nvm install` or `nvm add`, but just `nvm use`. Downloading a new version doesn't usually take more than a few seconds, and once it's downloaded it goes straight into the cache. That's also why `nvm ls` lists you everything you can use (switch to)—whether that requires a new download or not is not important. 

I prefer the simple approach taken here, but I understand that there are cons to this approach, e.g., not everyone has a consistently fast internet connection.

Does that make sense to you @rwwagner90 @JGJP?

**Comment by JGJP** [comment]
To me it feels like trying to reinvent something that's already established, I think I'm probably not the only one that came from regular nvm and had to change my mode of thinking. The regular expressions are quite tedious to type and I can't filter the results by LTS. Maybe you can create a flag that gives this full output? Across all CLIs `ls` commands usually default to what's on your system.

**Comment by jorgebucaran** [comment]
> To me it feels like trying to reinvent something that's already established

And what's wrong with that? I built this for fun, and because I couldn't be bothered to learn the original nvm completely, so it shouldn't come as a surprise that nvm and fish-nvm work differently. I didn't intend feature parity and I still don't.

 > Maybe you can create a flag that gives this full output? Across all CLIs ls commands usually default to what's on your system.

That wouldn't be hard to do, but it would be inconsistent with the project. fish-nvm doesn't have this notion of "installed" vs "installable" versions. `nvm ls` simply lists all the node versions you can use/switch to. Yes, we'll have to download any version that is not already in the cache, but that's just an implementation detail.

Having said that, [consider creating a fish abbreviation](https://fishshell.com/docs/current/cmds/abbr.html).


> The regular expressions are quite tedious to type and I can't filter the results by LTS

There isn't currently a way to filter the results to LTS releases only, but [you can filter some of the output](https://github.com/jorgebucaran/fish-nvm#listing-versions). Now, may I ask why you want to list the available LTS versions when you can just `nvm use lts` to get the latest LTS release?

**Comment by JGJP** [comment]
> Now, may I ask why you want to list the available LTS versions when you can just nvm use lts to get the latest LTS release?

Your docs show that there is an lts for each named version of Node, some projects won't build on the current lts, and just picking a version number to install feels arbitrary.

I'm ok with just accessing the regular nvm via another means that is not `fish-nvm` because it's your prerogative to do what you want with your package, but I didn't make this issue, you should probably expect to hear similar questions in the future because the naming of your project and the "close but not quite" syntax is somewhat uncomfortable.

**Comment by ljharb** [comment]
There’s 5 LTS streams currently, and a 6th comes out in October; “LTS” isn’t a single thing.

**Comment by jorgebucaran** [comment]
@JGJP This kind of entitlement is what ruins open source for some people. I'm going to address this issue one more time hoping it helps people seeing this later, but we're done here.

> Your docs show that there is an lts for each named version of Node

Hmm, don't think so. 

> ...some projects won't build on the current lts, and just picking a version number to install feels arbitrary.

No need to do that. 

If you run `nvm use lts`, you'll get the latest LTS release (12.16.2).
If you run `nvm use carbon` you'll get the latest Carbon (8.17.0).
If you run `nvm use dubnium`, you'll get the latest Dubnium (10.20.1).
If you run `nvm use 10`, you'll get (10.20.1) as well.
If you run `nvm use 10.20` you'll also get (10.20.1).
If you run `nvm use 10.15` you'll get (10.15.3) instead.
If you run `nvm use 10.15.1` you'll get (10.15.1) instead.

**Comment by jorgebucaran** [comment]
I just released [2.0](https://github.com/jorgebucaran/nvm.fish/releases/tag/2.0.0). Now there are `nvm list` and `nvm list-remote` commands that print the locally installed Node versions and versions available to download respectively. Both commands accept a regular expression to filter the output too.

See the [README](https://github.com/jorgebucaran/nvm.fish) for documentation. 👋
