### ISSUE TITLE
reinstall-packages-from?

### ISSUE THREAD

**Issue by deepfriedmind** [jorgebucaran/nvm.fish#134]
When updating to the latest node in nvm, I'm used to doing `nvm install node --reinstall-packages-from=node`. Is there any way to achieve the same result in nvm.fish?

**Comment by jorgebucaran** [comment]
What does that do?

**Comment by jorgebucaran** [comment]
No, there's no way to do that out of the box. But what does that flag do exactly?

**Comment by deepfriedmind** [comment]
It migrates global packages from the current install to the new one. 

See: https://github.com/nvm-sh/nvm#migrating-global-packages-while-installing

**Comment by jorgebucaran** [comment]
This will do the trick. I'm not sure I want to add a flag just to do that. What do you think?

```fish
set --local pkgs (string split / --fields=10 -- $nvm_data/$nvm_current_version/lib/node_modules/*)
nvm install latest && npm install --global $pkgs
```

**Comment by jorgebucaran** [comment]
This will do the trick.

```fish
set --local pkgs (string split / --fields=10 -- $nvm_data/$nvm_current_version/lib/node_modules/*)
nvm install latest && npm install --global $pkgs
```
 I'm not sure I want to add a flag just to do that. What do you think?

**Comment by ljharb** [comment]
That won't handle linked packages, which nvm does handle, nor will it preserve version numbers (i think).

**Comment by deepfriedmind** [comment]
> This will do the trick.
> 
> ```fish
> set --local pkgs (string split / --fields=10 -- $nvm_data/$nvm_current_version/lib/node_modules/*)
> nvm install latest && npm install --global $pkgs
> ```
> 
> I'm not sure I want to add a flag just to do that. What do you think?

`string split` doesn't have a `fields` option so the command fails. 

I'm currently doing something similar however:
```fish
set -l npmPackages (npm list -g --parseable --depth=0 | sed '1d' | awk '{gsub(/\/.*\//,"",$1); print}')
nvm install latest && npm install -g $npmPackages
```
Unfortunately, this workaround will re-install all packages even if no new node version was installed.

**Comment by jorgebucaran** [comment]
My bad, `--fields` is only available in Fish 3.2. In that case use:

```fish
set --local pkgs (string match --regex -- '[^/]+$' $nvm_data/$nvm_current_version/lib/node_modules/*)
nvm install latest && npm install --global $pkgs
```

**Comment by jorgebucaran** [comment]
Preserving version numbers is slower since we need to use `npm`:

```fish
set --local pkgs (npm list --global --depth=0 | string match --regex -- "\w+@[^\s]+\$")
nvm install latest && npm install --global $pkgs
```

Handling linked packages is much more involved:
 1. Save current version to a local variable.
 2. Grab the path from `foobar@1.2.1 -> /home/jb/foobar`.
 3. `nvm install VERSION`.
 4. Copy symlink to $nvm_current_version/lib/node_modules.

**Comment by jorgebucaran** [comment]
My bad, `--fields` is only available in Fish 3.2. In that case use:

```fish
set --local pkgs (string match --regex -- '[^/]+$' $nvm_data/$nvm_current_version/lib/node_modules/*)
nvm install latest && npm install --global $pkgs
```
Preserving version numbers is slower since we need to use `npm`:

```fish
set --local pkgs (npm list --global --depth=0 | string match --regex -- "\w+@[^\s]+\$")
nvm install latest && npm install --global $pkgs
```

Handling linked packages is much more involved:
 1. Copy `$nvm_current_version` to local variable
 2. Grab the path from `foobar@1.2.1 -> /home/jb/foobar`
 3. `nvm install VERSION`
 4. Copy symlink to $nvm_current_version/lib/node_modules

**Comment by jorgebucaran** [comment]
My bad, `--fields` is only available in Fish 3.2. 

For 3.0 or 3.1 we can use `string match` instead:

```fish
set --local pkgs (string match --regex -- '[^/]+$' $nvm_data/$nvm_current_version/lib/node_modules/*)
nvm install latest && npm install --global $pkgs
```
Preserving version numbers is slower since we need to use `npm`:

```fish
set --local pkgs (npm list --global --depth=0 | string match --regex -- "\w+@[^\s]+\$")
nvm install latest && npm install --global $pkgs
```

Handling linked packages is much more involved:
 1. Copy `$nvm_current_version` to local variable
 2. Grab the path from `foobar@1.2.1 -> /home/jb/foobar`
 3. `nvm install VERSION`
 4. Copy symlink to the current lib/node_modules

**Comment by deepfriedmind** [comment]
> ```fish
> set --local pkgs (npm list --global --depth=0 | string match --regex -- "\w+@[^\s]+\$")
> ```

That regex breaks on `-`. `"[\w,-]+@[^\s]+\$"` works.

Anyhoo, it would be nice to have the same functionality as `reinstall-packages-from` but I'm fine with working around it. Thanks for your time.

**Comment by jorgebucaran** [comment]
I'm not entirely opposed to adding this flag yet. Let me see how much code we'd end up with first. 👌

**Comment by ujwal-setlur** [comment]
any updates on this? This would be really useful.

**Comment by jorgebucaran** [comment]
Sorry, I won't be working on this so I'm closing. See [this comment](https://github.com/jorgebucaran/nvm.fish/issues/134#issuecomment-758174380) for a workaround. 

Feel free to send me a PR if you have a working solution, but I can't promise that too will get merged. We'll see.
