### ISSUE TITLE
lots of errors on install

### ISSUE THREAD

**Issue by mesqueeb** [jorgebucaran/nvm.fish#137]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3253920/106546902-81d56600-654f-11eb-8000-300351814388.png">

**Comment by jorgebucaran** [comment]
It seems you are still using Fisher `3.x`, which is no longer supported. See how to upgrade here https://github.com/jorgebucaran/fisher/issues/652.

Once you have Fisher 4.2 or later in your system, you should be able to proceed with the installation. Also, make sure you are not unintentionally running [_that_](https://github.com/nvm-sh/nvm) nvm, since you don't need it to use this plugin.

Let me know if you still run into any issues! 💯
