### ISSUE TITLE
This seems like a downgrade in usability compared to fnm :((

### ISSUE THREAD

**Issue by padurean** [jorgebucaran/nvm.fish#81]
**1. How can i view the versions that i already installed without looking in `~/.config/nvm`?**
`fnm` showed these by running it without any argument if i remember correctly (unlike `fnm/nvm ls` which lists all available versions)
**2. How can i remove an installed version of node?**
Unlike `fnm`, the new `nvm` does not have a `rm` option anymore :(

**Comment by jorgebucaran** [comment]
1. Why do you need to know versions you've ~~installed~~ **used** before?
2. What do you need `rm` for?

**Comment by padurean** [comment]
1. I need to know the versions i installed before so that i can remove them after i don't need them anymore - e.g. after i install a newer version (with `nvm use`) and i test that my projects work fine with it, so i don't need the older one anymore.
2. See my answer to 1. above: i need `rm` to remove a version that i don't need anymore. Otherwise node installations will just pile up in the `~/.config/nvm` folder. I thought it makes sense that if a tool provides the possibility to "install" something, it should also provide the possibility to "uninstall" it, not leaving the user with navigating folders to remove binaries and update config files as the only options (fortunately, as far as i realise, there's no need for the latter with `nvm` as `nvm use` will update the path so then any older version can just be removed manually from the `~/.config/nvm/` folder).

Anyway, `fnm` had close to perfect usability. I never understood all the renaming and dropping of arguments (rm, list installed versions) that took place :(

**Comment by jorgebucaran** [comment]
I said "installed" above. Should've said, "used".  

> @padurean i need rm to remove a version that i don't need anymore

Don't need it? Forget it! Node.js releases are tiny in relation to my storage capacity so I don't have to worry about removing previously downloaded releases while using this program. 

I don't care about versions I've used before, because I never remove them. I never needed that level of granularity. I `nvm use` the version I want to switch to and that's it. 

If I really wanted to, I could `rm -rf ~/.config/nvm`, or if I had enough of `nvm` I'd uninstall it, going back to system node (had there been one).

---

FYI the previous fnm kept a cache in `~/.cache/nvm`, so your downloads still "piled up".

**Comment by jorgebucaran** [comment]
> @padurean ...not leaving the user with navigating folders to remove binaries and update config files as the only options

Options for...? Elaborate, please. I've never done that, so you may have been inadvertently wasting your time.

**Comment by jorgebucaran** [comment]
@padurean I'm happy to keep the conversation going, so feel free to add your comments when you have time. 

I'm closing since there's nothing actionable here, we're just exchanging opinions.
